# sample_path_simulate

## 定義 probability matrix

In [3]:
import numpy as np
import time

def p(x):
    if x == 0:
        out = np.random.choice([0, 1, 2], p=[0.1, 0.1, 0.8])
    elif x == 1:
        out = np.random.choice([0, 1, 2], p=[0.2, 0.2, 0.6])
    elif x == 2:
        out = np.random.choice([0, 1, 2], p=[0.3, 0.3, 0.4])
    return out




## 計算 100 個 $X_{10000}$

In [11]:
start_time = time.time()
A = []
for _ in range(100):
    start = 0
    for _ in range(10000):
        start = p(start)
    A.append(start)

execution_time = time.time() - start_time
print("Execution time:", execution_time, "seconds")
print(np.unique(A, return_counts=True)[1] / len(A))

Execution time: 11.04283094406128 seconds
[0.21 0.32 0.47]


## 計算 10000 個 $X_{100}$

In [12]:
start_time = time.time()
A = []
for _ in range(10000):
    start = 0
    for _ in range(100):
        start = p(start)
    A.append(start)

execution_time = time.time() - start_time
print("Execution time:", execution_time, "seconds")
print(np.unique(A, return_counts=True)[1] / len(A))

Execution time: 11.119113206863403 seconds
[0.2338 0.2288 0.5374]


## 計算 1 個 $X_{1} \sim X_{1000000}$

In [13]:
start_time = time.time()
A = np.zeros(1000001)
start = 0
for i in range(1, 1000001):
    start = p(start)
    A[i] = start

execution_time = time.time() - start_time
print("Execution time:", execution_time, "seconds")
print(np.unique(A, return_counts=True)[1] / len(A))

Execution time: 11.502929210662842 seconds
[0.23111277 0.23011877 0.53876846]


## 結論
從上述的計算時間可以看出其實 3 者的收斂速度沒有太大的差異